<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Persistence\" />
      <Folder Include="Repositories\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AuthSystemTemplate.Application\AuthSystemTemplate.Application.csproj" />
      <ProjectReference Include="..\AuthSystemTemplate.Domain\AuthSystemTemplate.Domain.csproj" />
    </ItemGroup>

</Project>
